// Package cli provides the command-line interface for cfgctl.
package cli

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"
)

func newCleanCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "clean [provider...]",
		Short: "Clean up generated configuration files",
		Long: `Remove configuration files generated by one or more providers.

Examples:
  cfgctl clean aws
  cfgctl clean aws kubernetes`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}

			if err := validateProviders(args); err != nil {
				return err
			}

			ctx := context.Background()

			fmt.Println()
			for _, providerName := range args {
				if err := engine.CleanProvider(ctx, providerName); err != nil {
					return fmt.Errorf("failed to clean %s: %w", providerName, err)
				}
				fmt.Printf("  %s %s\n", labelStyle.Render("Cleaned:"), sectionStyle.Render(providerName))
			}
			fmt.Println()

			return nil
		},
	}

	return cmd
}
