package core

import (
	"context"
	"fmt"
	"sync"
	"time"
)

// Provider defines the interface that all configuration providers must implement.
// Each provider is responsible for generating, backing up, restoring, and cleaning
// its specific configuration files.
type Provider interface {
	// Name returns the unique identifier for this provider.
	// Examples: "aws", "kubernetes", "ssh"
	Name() string

	// Validate checks if all prerequisites for this provider are met.
	// This includes checking for required commands, configuration files,
	// environment variables, etc.
	Validate(ctx context.Context) error

	// Generate creates the configuration files for this provider.
	// Returns a Result containing details about what was generated.
	Generate(ctx context.Context, opts *GenerateOptions) (*Result, error)

	// Backup creates a backup of existing configuration files.
	// Returns the path to the backup location.
	Backup(ctx context.Context) (string, error)

	// Restore recovers configuration from a backup.
	// The backupPath should be a path returned by Backup().
	Restore(ctx context.Context, backupPath string) error

	// Clean removes all configuration files generated by this provider.
	// This is useful for testing or complete reset scenarios.
	Clean(ctx context.Context) error
}

// BackupDecider allows providers to determine whether a backup is needed.
type BackupDecider interface {
	NeedsBackup(opts *GenerateOptions) (bool, error)
}

// Checker is an optional interface providers can implement to verify live connectivity.
type Checker interface {
	Check(ctx context.Context) ([]CheckResult, error)
}

// CheckStatus is the outcome of a single check target.
type CheckStatus int

// CheckStatus values for connectivity check outcomes.
const (
	CheckStatusOK   CheckStatus = iota // reachable and healthy
	CheckStatusWarn                    // valid but degraded, e.g. credential expiring soon
	CheckStatusFail                    // unreachable or invalid
)

// CheckResult holds the outcome of checking a single target within a provider.
type CheckResult struct {
	Target  string
	Status  CheckStatus
	Latency time.Duration // zero means not measured
	Note    string
}

// GenerateOptions contains options that can be passed to Generate.
type GenerateOptions struct {
	// DryRun indicates whether to simulate generation without making changes.
	DryRun bool

	// Force indicates whether to overwrite existing configurations.
	Force bool

	// Replace indicates whether to discard existing manually-added content and
	// write only cfgctl-managed entries. Providers that support preservation
	// (AWS, Steampipe, SSH) skip their merge logic when this is true.
	Replace bool

	// Verbose indicates whether to output detailed progress information.
	Verbose bool

	// Config contains provider-specific configuration data.
	Config ProviderConfig

	// Status receives progress updates during generation.
	// Providers should call UpdateStatus to report what they are doing.
	Status StatusUpdater
}

// ProviderConfig is a marker interface for provider-specific configuration.
// Each provider defines its own concrete implementation.
type ProviderConfig interface {
	// Validate checks if the provider configuration is valid.
	Validate() error
}

// EnabledProviderConfig reports whether a provider is enabled.
type EnabledProviderConfig interface {
	IsEnabled() bool
}

// Result contains information about what was generated by a provider.
type Result struct {
	// Provider is the name of the provider that generated this result.
	Provider string

	// DryRun indicates this result came from a dry-run (no files were written).
	DryRun bool

	// FilesCreated lists all files that were created or modified.
	// In dry-run mode, these are the files that would have been created.
	FilesCreated []string

	// FilesSkipped lists files that were skipped (e.g., already exist and no --force).
	FilesSkipped []string

	// BackupPath is the location of the backup, if one was created.
	BackupPath string

	// Warnings contains any non-fatal issues encountered during generation.
	Warnings []string

	// Metadata contains provider-specific result data.
	Metadata map[string]interface{}
}

// ProviderConfigFactory is a function that creates a ProviderConfig from a raw map.
type ProviderConfigFactory func(map[string]interface{}) (ProviderConfig, error)

var (
	configFactories   = make(map[string]ProviderConfigFactory)
	configFactoriesMu sync.RWMutex
)

// RegisterProviderConfigFactory registers a factory function for a provider's configuration.
func RegisterProviderConfigFactory(providerName string, factory ProviderConfigFactory) {
	configFactoriesMu.Lock()
	defer configFactoriesMu.Unlock()
	configFactories[providerName] = factory
}

// ProviderConfigFromMap converts a raw map to a typed ProviderConfig based on the provider name.
func ProviderConfigFromMap(providerName string, raw map[string]interface{}) (ProviderConfig, error) {
	configFactoriesMu.RLock()
	factory, exists := configFactories[providerName]
	configFactoriesMu.RUnlock()

	if !exists {
		return nil, fmt.Errorf("no config factory registered for provider %q", providerName)
	}

	return factory(raw)
}
